### ISSUE TITLE
Fractions are converted to unnecessarily precise decimals

### ISSUE THREAD

**Issue by skykooler** [rveciana/obsidian-cooklang#1]
I have a recipe that calls for a third of a cup of rice vinegar, which is written as per the cooklang spec as `@rice vinegar{1/3%cup}`.  This gets rendered in the ingredient list as `0.333333333333333 cup rice vinegar`. This should probably be truncated to fewer digits - I seriously doubt that people need a resolution of femtocups.

**Comment by neongrey** [comment]
i don't find the decimalization desirable at all, tbh-- if I note an ingredient down as a fraction, say, `@black pepper{1/8%tsp}` it'll be because my measuring spoons are labeled in fractions and `0.125 tsp black pepper` is just gonna be a hassle to deal with in the kitchen. 

(even if in this specific case I'm going to completely disregard what the recipe says and just freehand crank the grinder because this recipe is clearly underseasoning; there's other recipes where fractional teaspons actually matter, this is just from the one I was just transcribing)

**Comment by rveciana** [comment]
I think that there are two topic here.
- If we show decimals, they have to be truncated for sure, like 0.3 instead of 0.33333333333333
- You both are right. Some people will prefer the decimals and others the fractions. The library I'm using, cooklang-ts, converts any fraction into decimals. What I will do is adding an options at settings so everyone can choose their favourite way to see it.

**Comment by rveciana** [comment]
It should be available now, if you use version 0.0.10
